service: serverless-mac-demo

frameworkVersion: ">=1.8.0 <2.0.0"

custom:
  stage: dev
  
provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Resource:
      - "Fn::Join":
        - ""
        - - "arn:aws:dynamodb:"
          - {Ref: "AWS::Region"}
          - ":"
          - {Ref: "AWS::AccountId"}
          - ":table/"
          - Ref: StudentDB
      - "Fn::Join":
        - ""
        - - "arn:aws:dynamodb:"
          - {Ref: "AWS::Region"}
          - ":"
          - {Ref: "AWS::AccountId"}
          - ":table/"
          - Ref: StudentDB
          - '/index/*'
      - "Fn::Join":
        - ""
        - - "arn:aws:dynamodb:"
          - {Ref: "AWS::Region"}
          - ":"
          - {Ref: "AWS::AccountId"}
          - ":table/"
          - Ref: KeySequenceDB
      - "Fn::Join":
        - ""
        - - "arn:aws:dynamodb:"
          - {Ref: "AWS::Region"}
          - ":"
          - {Ref: "AWS::AccountId"}
          - ":table/"
          - Ref: KeySequenceDB
          - '/index/*'
      Action:
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:Scan
      - dynamodb:Query
          
functions:
  putStudent:
    handler: python/put_student.handler
    events:
    - http:
        authorizer:
          name: pool_auth
          arn: arn:aws:cognito-idp:ap-southeast-1:021903227276:userpool/ap-southeast-1_8aQkNdVF9
        path: /put-student
        method: post
        cors: true
  updateStudent:
    handler: python/update_student.handler
    events:
    - http:
        authorizer:
          name: pool_auth
          arn: arn:aws:cognito-idp:ap-southeast-1:021903227276:userpool/ap-southeast-1_8aQkNdVF9
        path: /update-student
        method: post
        cors: true
  deleteStudent:
    handler: python/delete_student.handler
    events:
    - http:
        authorizer:
          name: pool_auth
          arn: arn:aws:cognito-idp:ap-southeast-1:021903227276:userpool/ap-southeast-1_8aQkNdVF9
        path: /delete-student
        method: post
        cors: true
  searchStudent:
    handler: python/search_students.handler
    events:
    - http:
        authorizer:
          name: pool_auth
          arn: arn:aws:cognito-idp:ap-southeast-1:021903227276:userpool/ap-southeast-1_8aQkNdVF9
        path: /search-student
        method: get
        cors: true
  authenticatedApi:
    handler: python/authenticated_api.handler
    events:
    - http:
        authorizer:
          name: pool_auth
          arn: arn:aws:cognito-idp:ap-southeast-1:021903227276:userpool/ap-southeast-1_8aQkNdVF9
        path: /authenticated-api
        method: get
        cors: true
  unauthenticatedApi:
    handler: python/unauthenticated_api.handler
    events:
    - http:
        path: /unauthenticated-api
        method: get
        cors: true

resources:
  Resources:
    StudentDB: ${file(resources/student-db.yml)}
    KeySequenceDB: ${file(resources/key-sequence-db.yml)}
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'

package:
  exclude:
  - .serverless/**
  - resources/**
  - /*.yml